### ISSUE TITLE
TypeError: Cannot redefine property: Hub

### ISSUE THREAD

**Issue by nacimgoura** [ixartz/Astro-boilerplate#13]
Hello,
after `npm install` I have an error when I run `npm run dev` :

![image](https://github.com/ixartz/Astro-boilerplate/assets/9990521/f90f3612-2386-4e7d-81f0-d028bceb0cc3)

**Comment by ixartz** [comment]
@nacimgoura I'm not able to reproduce the error, could you give me more information?

**Comment by nacimgoura** [comment]
> @nacimgoura I'm not able to reproduce the error, could you give me more information?

I didn't do much, I cloned the project. Then ‘npm install‘ and ‘npm run dev‘ (with nodejs 20.6.0)

**Comment by ixartz** [comment]
@nacimgoura I just made a clean and fresh install, it's working. Unfortunately, I'm not able to reproduce it.
