### ISSUE TITLE
Images are not displayed when deploying to GitHub Pages through Actions

### ISSUE THREAD

**Issue by icutter** [ixartz/Astro-boilerplate#15]
I'm using the official Astro workflow for GitHub Action.
Build and deployment jobs are both completed with no errors.
  
When accessing the deployed page no images are displayed, and in the browser console a `404 error` is logged for each of them.
  
Images not loading:
![Screenshot 2023-12-27 214425](https://github.com/ixartz/Astro-boilerplate/assets/33135141/a9190f7f-cc64-4cf4-8cfe-53a6f47a5538)
  
Errors in browser console:
![Screenshot 2023-12-27 214557](https://github.com/ixartz/Astro-boilerplate/assets/33135141/4274ba3b-94f4-40c1-a449-2ac83520bc84)

**Comment by ixartz** [comment]
I don't have any experience working with GitHub Page and GitHub Actions using this template. Technically, you should have any issue using GitHub Page. All static hosting provided should be supported.

As a workaround, I would suggest to use Netlify: https://github.com/ixartz/Astro-boilerplate#deploy-to-netlify. I have tested myself

**Comment by icutter** [comment]
Still no luck with GitHub Pages, but I got it working on Netlify. Thank you!
