### ISSUE TITLE
New route gives error 

### ISSUE THREAD

**Issue by Bijig0** [ixartz/Astro-boilerplate#16]
I want to add another page, projects. I added it in /src/pages, and inside added a directory pages, with a file [...page].astro. It seems if I create any page that isn't named posts (the one given by the template), I get an eslint error? Why is this?

```
arsing error: "parserOptions.programs" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided program instance(s): src/pages/projects/[...page].astro
```
<img width="1084" alt="Screenshot 2023-12-30 at 8 58 43 PM" src="https://github.com/ixartz/Astro-boilerplate/assets/76978374/82a3ab33-a18d-4ecf-a0f7-893d4c91e5e8">

This is the error

**Comment by Bijig0** [comment]
bump

**Comment by ixartz** [comment]
This is extremely strange, currently I do have any explanation why you get this error. There isn't nothing special in the settings which can explain the error.

Currently, don't have the time to dig into the error. So, totally open to suggestion.
