### ISSUE TITLE
I get errors from 'sharp' and 'xml2js' dependencies

### ISSUE THREAD

**Issue by GeoCodee** [ixartz/Astro-boilerplate#17]
I get errors when I run 'npm run dev' because of these two dependencies. I tried using 'npm audit fix --force' but it doesn't fix the issue

**Comment by GeoCodee** [comment]
![vulnerabilities](https://github.com/ixartz/Astro-boilerplate/assets/78028271/2e4deb89-d95b-4f0e-b9c1-f288dcc3ad2f)

**Comment by ixartz** [comment]
@GeoCodee, could you make a fresh and clean git clone of the project. Then, run `npm run install` and `npm run dev`.

If you get any errors, could you share with me the errors?
