### ISSUE TITLE
astro-imagetools issue on blog images

### ISSUE THREAD

**Issue by barrenechea** [ixartz/Astro-boilerplate#2]
When browsing https://creativedesignsguru.com/demo/astro-boilerplate/posts/ you can see on the network requests that the images are not being processed by `astro-imagetools` as the stock images get downloaded into the client.

The only image being transformed is located here: https://creativedesignsguru.com/demo/astro-boilerplate/posts/sixth-post/ so it seems to only be able to parse embedded images in a markdown file.

Any clues?

**Comment by ixartz** [comment]
I mostly use React in this project with Astro. And, unfortunately, there is no component in `astro-imagetools` for React. So, what is why `astro-imagetools` can only work with markdown file.

But, I'm totally open to suggestion. This is my first project in Astro.
