### ISSUE TITLE
Inconsistency for trailing slash in links from BlogGallery and ProjectList

### ISSUE THREAD

**Issue by zzikkzzakk** [ixartz/Astro-boilerplate#9]
There is an inconsistent behaviour in links to posts: 
From the ProjectList the links have a trailing slash, e.g. `/posts/my-post/`
in links from BlogGallery there is none, e.g. `/posts/my-post`

On production I need a trailing slash in all links.
So in `astro.config.mjs` I had to set
`trailingSlash: 'always'`
and it worked.

And I had to append the trailing slash in the NavBar links, e.g.
`<NavMenuItem href="/posts/">Blog Posts</NavMenuItem>`

**Comment by ixartz** [comment]
@zzikkzzakk Thank you for suggesting this change. It'll definitively make the output more consistent.

If you want, you can create a PR and I'll merge it.

**Comment by Izocel** [comment]
Some are fixed here
#12

**Comment by ixartz** [comment]
@Izocel has fixed the issue. Thank you!
